### ISSUE TITLE
Merge / delete old profile

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#107]
Vercom/PushPushGo - they’ve registered twice with different domains and have now two accounts on our website:

- https://ecommerceberlin.com/exhibitors/pushpushgocom (old one, to be deleted)
- https://ecommerceberlin.com/exhibitors/vercompl (correct one, with good location nr)

**Comment by az** [comment]
@jprzybylski4 i am not deleting any older accounts for data integrity reasons..please ALWAYS focus on the problem and do not try to think for myself

(PPG was bought by /merged with vercom)

WHAT IS THE PROBLEM HERE? doubled brand name on the list or what?

**Comment by az** [comment]
@jprzybylski4 do you receive notifications?

**Comment by jprzybylski4** [comment]
They emailed us asking us to delete the old profile. 
At the moment both profiles show details of Pushpushgo - if you don't want to delete the profile can we please merge them under the new (correct) one?

**Comment by az** [comment]
@jprzybylski4 if i email you about giving me 1mln $ - will you?

asking again WHAT IS THE PROBLEM here? because i dont think the structure of the database is anybody's domain but mine

**Comment by az** [comment]
here are the examples of "problems" @jprzybylski4 

from exhibitor's POV

* we can see double entry on exhibitors list (not applicable here)
* we see our profile indexed in search engines twice

from our side

* we didnt notice the brand existed previously and attached new company and the client filled in some data already 

if you want solutions - please define problems. ALWAYS. please dont use the phrases like "delete data", "merge data" because these are really out of yr scope

**Comment by jprzybylski4** [comment]
That was actually this case:
we can see double entry on exhibitors list (not applicable here).
Their entry was visible twice on the list on HP and their logotype was visible twice on https://ecommerceberlin.com/exhibitors when I was submitting the issue

**Comment by az** [comment]
perfect...so it was resolved via "hide from the list" mechanism - sorted out via https://github.com/ecommerceberlin/ecommerceberlin.com/issues/106 

if you would define the issue by a problem "brand name is shown twice" we would save about 1hr of time!

so one more time..please do not use the phrases merge/delete because our system is not a word document - always focus on visible problem (account manager's POV or client's POV)
