### ISSUE TITLE
Additional services email #2

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#111]
Subject ENG: E-commerce Berlin Expo 22: Additional services reminder
Subject DE: E-commerce Berlin Expo - Erinnerung an zusätzlichen Standdiensten

[additional-services-emails-#2.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/7891069/additional-services-emails-.2.zip)

Please let me know if the files are prepared correctly. The first paragraph introduces the account manager - I'm unsure if you can fill in the AM name using some kind of a "snippet". If you cannot do it this way I will be happy to prepare 3 separate files. 

Also, due to German terms, there are two separate files to be sent in DE - one for DK+GY and one for MM companies.

**Comment by az** [comment]
@jprzybylski4 

world seems a better place if keep simple things ....simple?

only two files can be processed (language is the criteria, right? ) 

re account manager -there is only a placeholder {{$footer}} for auto pasting name and contact data (so i do advise to point to the footer and refrain from poetry in the invocation :)

please fix {{$profile->translate("[[fname]]") to {{ array_get($profile, "fname") }} as translate is not used since over a yr

**Comment by jprzybylski4** [comment]
Please find the updated files attached
[additional-services-emails-#2-fixed.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/7896019/additional-services-emails-.2-fixed.zip)
s

**Comment by az** [comment]
thx. scheduled for TUE 10-12.
