### ISSUE TITLE
(EMAIL) Exhibitors - how_to_prepare_for_expo $30$

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#129]
Please schedule and send the attached emails.

EN: E-commerce Berlin Expo 2022 - are you all prepared? We’ve got some tips for you!
DE: E-commerce Berlin Expo 2022 - bist du schon vorbereitet? Wir haben einige Tipps für dich!

[ebe6-how_to_prepare_for_expo.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8125225/ebe6-how_to_prepare_for_expo.zip)

**Comment by az** [comment]
@peterecommberlin OK

i will confirm NEXT WEEK

btw: status of unassigned account manager - i hope there is someone in charge of updating it

![E-commerce Berlin Expo | Berlin | May, 2022 2022-02-24 12-50-10](https://user-images.githubusercontent.com/2198/155518711-ee041b21-bf4d-487d-b781-bca618b8445b.jpg)

cc @jprzybylski4

**Comment by peterecommberlin** [comment]
@az fixed. 

the odd thing with CoverGenius and Storyblok - we had added account managers a long time ago i think. Both of them have some additional packages (premium services)... maybe that's why they are listed here.

**Comment by az** [comment]
![purchases 2022-02-24 13-33-08](https://user-images.githubusercontent.com/2198/155524835-ed071f63-b0ef-4f2f-8fb1-c16903f86e91.jpg)

odd things (almost) never happen - just human failures :)

as i can see a company is not assigned to one of the purchases..... 

**company must be assigned to ANY purchase of tickets marked by role exhibitor (i assume vipzone ticket has a role exhibitor)**

**Comment by az** [comment]
![purchases 2022-02-24 13-36-50](https://user-images.githubusercontent.com/2198/155525435-c6493ab0-bd04-4617-b5ef-1b1db44c93b5.jpg)

covergenius same story @peterecommberlin 

ticket has role "exhibitor" - company should be assigned (otherwise we may encounter an error and the other side effect is that the company cannot see the big picture in their panel....only some purchases are visible)

**Comment by peterecommberlin** [comment]
just for the sake of clarity... i will drop you my pov on this. Maybe i'm wrong but would be good to be on the same page :) 

Companies are allowed to order services like vip zone only if they are confirmed exhibitor. So... they already have one exhibitor account in the system (right?). If we turn on the EXPO button in the system then another one will be created, i think so?! To avoid the mess we didn't assign premium services to the exhibitor panel...

**Comment by az** [comment]
![Image 2022-02-24 14-10-05](https://user-images.githubusercontent.com/2198/155530165-2932c0ae-1681-4ca7-addc-6f6cb66ba1b5.jpg)

> Companies are allowed to order services like vip zone only if they are confirmed exhibitor.

that is business (!!!!) perspective totally not represented here

that would be only true in "admin context" WHEN YOU'D UPGRADE main purchase (a "booth") with some other stuff (ideally with ticket with role other than **exhibitor**...like **service_internal** or **service_external** or empty role)....that would literally mean "an additional item has been purchased by an exhibitor"...its valid when you upgrade stuff via account.... OR book things internally in the name of a company (via upgrade button).... 

we have other scenario here ... 2 independent bookings.

considering one example entity - COVERGENIUS

so at the moment you have 1 company (in business meaning!!!) but 2 exhibitors (and one is making problems when we are sending email newsletter)... why?

there are at least two separate registrations/purchases with tickets that are marked as "exhibitor" role (check the screenshot above) - this not considered as 1 company because one of the purchase has no company assigned (!)

from the admin side there 2 UNRELATED exhibitors (2 tickets with exhibitor role) but one has company assigned and the other not....

SO - the correct way of doing things is:

* ONLY tickets that are represented on the booking map (with a space) should have an exhibitor role
* All upgrades (from the business perspective) should have only service_internal or service_external role
* Every PAID purchase should have a company assigned 

@peterecommberlin @jprzybylski4

**Comment by az** [comment]
maybe you havent understood the "role" option of the tickets @peterecommberlin 

role is not "who can buy it" (we dont have any of such things in our system)...... role is a static tag so we could perform some stuff (like get all exhbitors from all events) without thinking of the  ticket's name or the ticket's tag used .... exhibitor in every event has a ticket with role exhbitor, similar "presenter", "contestant" etc.... otherwise i would need to adapt the code to ticket ids, tags or names on every event change.... but the whole system is based on ticket roles ("static names") also sending the newsletters 

sending newsletter is "get me all entities that purchased the tickets that has a role "exhibitor")

so the sending system took coffee snacks because of invalid role set....and shown an error because this "exhibitor" had no company assigned

**Comment by jprzybylski4** [comment]
@az account managers fixed in the new admin. 

Regarding your slack message - could we please add the link to calendly as a variable / placeholder?
It would also be great if we could add the same link in the AM's footer for future emails. 

DOMINIK: [https://calendly.com/dominik-ebe](https://calendly.com/gerome-ebe)
GEROME: https://calendly.com/gerome-ebe
MARTA: [https://calendly.com/marta-ebe](https://calendly.com/gerome-ebe)

**Comment by az** [comment]
@jprzybylski4 ok - we will expand the email footer with such info
