### ISSUE TITLE
(BUG) URL address issue in exhibitors profile - only "regular" domains are working  

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#130]
It's impossible to type different email addresses than "regular" .com into exhibitors' online profile.

e.g. 
Ecomin rebranded to empact.online and they we would like to update URL address 
i just used bitly to fix the problem (temporary solution)

https://empact.online/  
![Screenshot 2022-02-23 at 15 37 19](https://user-images.githubusercontent.com/35766428/155345164-1bf3bca3-14da-4bf8-929a-7508ccd75851.png)

**Comment by az** [comment]
@peterecommberlin 

* bad template (https://github.com/ecommerceberlin/ecommerceberlin.com/issues/96) , 
* BAD project 
* duplicate (https://github.com/ecommerceberlin/account.ecommerceberlin.com/issues/7 )
* i'm not fixing an old account.*** (@jprzybylski4 please inform at lease the core team members about our discussions)

i'm closing this issue (@jprzybylski4  please pass down to the team the way of doing things otherwise we will be always wild wild west)
