### ISSUE TITLE
(ACCOUNTING) ask masterclasses organizers to update their submissions

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#266]
when submission page update is DONE (https://github.com/ecommerceberlin/ecommerceberlin.com/issues/265) please send all masterclasses organizers to update their profiles

1. select them by tag - https://pages.ecommerceberlin.com/admin/filtered?tags=masterclass
2. select all
3. send email
4. IMPORTANT .... add https://ecommerceberlin.com/recall/[[token]]?goto=/masterclasses/edit in the contents of the message (token will be replaced by THEIR token)

**Comment by klaudia2209** [comment]
I talked to Fabien about it. 

Can we create the links on our own and send them in the e-mails? Could you show us the example of the proper link (with pasted token)? 

Fabien is already in touch with the speakers and it would be better to continue the communication this way, instead of creating a new thread and send it automatically (it often goes to SPAM folder).

**Comment by klaudia2209** [comment]
Done, links sent to the masterclasses' speakers

**Comment by az** [comment]
@klaudia2209 gr8 - i will be checking the results at /masterclasses/temp?q=

**Comment by az** [comment]
@klaudia2209 monitorujesz to? mamy 1 (prawie) kompletna https://ecommerceberlin.com/masterclasses/temp?q=

trzeba by puscic kolejny ping w pon/wt

gdybys przetlumaczyla stronke dla participanta to moznaby podmienic te dla organizatora z ta dla participanta i podeslac im jako miejsce gdzie wyladuje ich praca z uzupelnianiem profilu
